In [1]:
import pandas as pd

In [10]:
debt_county = pd.read_csv('household-debt-by-county.csv')
debt_msa = pd.read_csv('household-debt-by-msa.csv')
debt_state = pd.read_csv('household-debt-by-state.csv')

In [24]:
debt_county.head()
debt_county.info()
debt_county.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 329478 entries, 0 to 329477
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   year       329478 non-null  int64
 1   qtr        329478 non-null  int64
 2   area_fips  329478 non-null  int64
 3   low        329478 non-null  float64
 4   high       297292 non-null  float64
dtypes: float64(2), int64(3)
memory usage: 12.6 MB

(329478, 5)

In [27]:
debt_county.describe()

,year,qtr,area_fips,low,high
count,329478.000000,329478.000000,329478.000000,329478.000000,297292.000000
mean,2011.628910,2.485662,30401.454103,1.593439,1.774433
std,7.576909,1.122182,15151.017527,0.916173,0.793094
min,1999.000000,1.000000,1001.000000,0.000000,0.780000
25%,2005.000000,1.000000,18181.000000,1.010000,1.190000
50%,2012.000000,2.000000,29177.000000,1.580000,1.580000
75%,2018.000000,3.000000,45081.000000,2.150000,2.150000
max,2025.000000,4.000000,56045.000000,3.430000,3.430000

In [29]:
debt_county.isna().sum()

year             0
qtr              0
area_fips        0
low              0
high         32186
dtype: int64

In [30]:
debt_county.duplicated().sum()

np.int64(0)

In [31]:
debt_county.value_counts().sort_index

<bound method Series.sort_index of year  qtr  area_fips  low   high
2025  1    56045      1.58  1.82    1
1999  1    1001       1.82  2.15    1
           1003       1.82  2.15    1
           1005       0.00  0.78    1
           1007       2.61  3.43    1
                                   ..
           1031       1.19  1.37    1
           1033       0.78  1.01    1
           1035       1.01  1.19    1
           1037       1.19  1.37    1
           1039       1.01  1.19    1
Name: count, Length: 297292, dtype: int64>

In [12]:
debt_msa.head()

   year  qtr   cbsa   low  high
0  1999    1  10180  1.02  1.14
1  1999    1  10420  1.14  1.25
2  1999    1  10500  0.51  1.02
3  1999    1  10580  0.51  1.02
4  1999    1  10740  1.47  1.61

In [14]:
debt_state.head()

   year  qtr  state_fips   low  high
0  1999    1           1  0.40  1.11
1  1999    1           2  1.24  1.32
2  1999    1           4  1.32  1.40
3  1999    1           5  0.40  1.11
4  1999    1           6  1.60  1.72